name: task 1, three python packages test, lint and build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            module_a:
              - 'module_a/*.py'
              - 'module_a/package_module_a/*.py'
              - 'module_a/package_module_a/tests/*.py'
            module_b:
              - 'module_b/*.py'
              - 'module_b/package_module_b/*.py'
              - 'module_b/package_module_b/tests/*.py'

      - name: Install base dev deps and build for module_a
        if: ${{ steps.filter.outputs.module_a == 'true' }}

        run: |
          cd module_a
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile -r --allow-unsafe --no-header --annotation-style line -U requirements.in
          pip-sync requirements.txt
          pip install -e .

      - name: pylint with pylama for module_a
        if: ${{ steps.filter.outputs.module_a == 'true' }}
        run: |
          cd module_a
          pytest --pylama -v

      - name: Install base dev deps and build for module_b
        if: ${{ steps.filter.outputs.module_b == 'true' }}
        run: |
          cd module_b
          pip-compile -r --allow-unsafe --no-header --annotation-style line -U requirements.in
          pip-sync requirements.txt
          pip install build
          pip install -e .

      - name: pylint with pylama for module_b
        if: ${{ steps.filter.outputs.module_b == 'true' }}
        run: |
          cd module_b
          pytest --pylama -v
